### ISSUE TITLE
Tweak to make this work with GitLab Auto DevOps

### ISSUE THREAD

**Issue by cpilson** [guzmanoj/herokuish-install-chrome#1] opened 2020-11-25 11:27 UTC
I was getting permission denied errors. The solution is to change the line in package.json to explicitly call chmod +x and then run the script:

"heroku-prebuild": "chmod +x ./install-chrome.sh && ./install-chrome.sh"

**Comment by wall-street-dev** [comment] 2020-11-25 11:45
Hi @cpilson, I just committed the script again using the --chmod=+x flag...
Maybe that'll do.
I was not able to reproduce the original issue, though.

**Closed as completed** 2020-12-23 20:13 UTC
